-- AlterTable
ALTER TABLE "internships" ALTER COLUMN "salaryMin" SET DATA TYPE BIGINT,
ALTER COLUMN "salaryMax" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "jobs" ALTER COLUMN "salaryMin" SET DATA TYPE BIGINT,
ALTER COLUMN "salaryMax" SET DATA TYPE BIGINT;
